### ISSUE TITLE
JpegDecoder better support

### ISSUE THREAD

**Issue by erictuvesson** [yufeih/Nine.Imaging#5]
Are you thinking of adding RGBA support to JpegDecoder?

https://github.com/yufeih/Nine.Imaging/blob/master/src/Encoding/Jpeg/JpegDecoder.cs#L81

**Comment by yufeih** [comment]
JPEG with alpha channel?

**Comment by erictuvesson** [comment]
I'm sorry, the error message is confusing me. I have an image that is grayscale which is throwing that exception.

Edit: I also have a CMYK image.

**Comment by erictuvesson** [comment]
I am closing this issue and referring to #7 instead.
